name: Ci

on: [push, pull_request]

jobs:
  test-flake:
    runs-on: native

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Check flake
        run: nix flake check -L --show-trace
