{...}: {
  den.aspects.editors.emacs = {
    homeManager = {
      pkgs,
      lib,
      ...
    }: let
      hpkgs = pkgs.haskell.packages."ghc912";

      migrate = pkgs.go-migrate.overrideAttrs (oldAttrs: {
        tags = ["postgres"];
      });

      gruber-darker-theme = pkgs.emacsPackages.melpaBuild {
        pname = "gruber-darker-theme";
        version = "0.6";
        src = pkgs.fetchFromGitHub {
          owner = "rexim";
          repo = "gruber-darker-theme";
          rev = "master";
          hash = "sha256-9LcKIOwxUp0AQPM3+ajQlTCKyHBX9gpRzARE3LkzBxw=";
        };

        packageRequires = [];
      };

      flymake-golangci = pkgs.emacsPackages.melpaBuild {
        pname = "flymake-golangci";
        version = "1.0.2";
        src = pkgs.fetchFromGitea {
          domain = "codeberg.org";
          owner = "arouene";
          repo = "flymake-golangci.el";
          rev = "main";
          hash = "sha256-fgcoNN9j1AUcL+ChgRMVZHDHgn45w1+xzPYRKnfmSa4=";
        };
      };

      tools = with pkgs; [
        # Common
        coreutils
        direnv
        git
        # File format converter
        pandoc
        # Time tracking
        wakatime-cli

        # Language / LSP / formatter / debugger
        # Golang
        go
        gopls
        golangci-lint
        delve
        migrate
        go-swag
        # Nix
        nil
        alejandra
        # Bash
        shellcheck
        # Haskell
        hpkgs.ghc
        (lib.hiPrio hpkgs.cabal-install)
        hpkgs.cabal-add
        hpkgs.cabal-gild
        hpkgs.hoogle
        hpkgs.haskell-language-server
        hpkgs.fourmolu
        # Yaml
        yaml-language-server
        # JSON
        vscode-langservers-extracted
        # Docker
        dockerfile-language-server
        # C/C++/Clang
        clang-tools
        cmake
        # Java
        jdk25
        # Python3
        python3
        # NodeJS
        nodejs
      ];

      toolsPath = pkgs.lib.makeBinPath tools;

      initFragments = [
        ./emacs.d/config/00-bootstrap.el
        ./emacs.d/config/01-environment.el
        ./emacs.d/config/02-ligatures.el
        ./emacs.d/config/03-core.el
        ./emacs.d/config/04-navigation.el

        ./emacs.d/config/10-move-text.el
        ./emacs.d/config/20-theme.el
        ./emacs.d/config/21-minibuffer.el
        ./emacs.d/config/22-structural-editing.el

        ./emacs.d/config/30-git.el
        ./emacs.d/config/31-vundo.el
        ./emacs.d/config/32-environment-project.el
        ./emacs.d/config/33-dired.el
        ./emacs.d/config/34-project.el
        ./emacs.d/config/35-dashboard.el
        ./emacs.d/config/36-wakatime-yasnippet.el

        ./emacs.d/config/40-company.el
        ./emacs.d/config/41-eglot.el
        ./emacs.d/config/42-languages.el

        ./emacs.d/config/50-vterm.el
        ./emacs.d/config/51-hl-todo.el

        ./emacs.d/config/60-org.el
        ./emacs.d/config/61-newsticker.el
      ];

      initEl = ''
        ;;; init.el --- Generated by Home Manager -*- lexical-binding: t; -*-
        ;;; Commentary:
        ;; Do not edit ~/.config/emacs/init.el directly.
        ;; Edit modules/home/emacs/emacs.d/config/*.el instead.
        ;;; Code:

        ${pkgs.lib.concatMapStringsSep "\n\n" builtins.readFile initFragments}

        (provide 'init)
        ;;; init.el ends here
      '';
    in {
      # Home manager installation
      home.packages = tools;

      # Emacs configurations
      programs.emacs = {
        enable = true;

        extraPackages = epkgs:
          with epkgs; [
            # Editing / UI.
            move-text
            paredit
            multiple-cursors
            vundo
            hl-todo
            doom-themes
            gruber-darker-theme
            gruvbox-theme
            nerd-icons
            nerd-icons-dired
            dashboard

            # Completion.
            vertico
            orderless
            smex
            company

            # Git.
            magit
            forge
            diff-hl

            # Environment / project integration.
            envrc
            inheritenv
            dired-toggle
            trust-manager

            # Snippets / activity tracking.
            yasnippet
            yasnippet-snippets
            wakatime-mode

            # Development.
            dape
            go-mode
            flymake-golangci
            nix-mode
            haskell-mode
            markdown-mode
            proof-general
            company-coq

            # Terminal.
            vterm
            vterm-toggle

            # Org extensions.
            verb
            impostman
            org-modern

            # Grammars used by built-in tree-sitter major modes.
            (treesit-grammars.with-grammars (grammars:
              with grammars; [
                tree-sitter-yaml
                tree-sitter-json
                tree-sitter-dockerfile
              ]))
          ];
      };

      # Exact Nix store paths required by init.el at runtime.
      home.file.".emacs.d/nix-vars.el".text = ''
        ;;; nix-vars.el --- generated by Home Manager -*- lexical-binding: t; -*-
        (defconst my/nix-tool-path "${toolsPath}")
        (defconst my/nix-coreutils-ls "${pkgs.coreutils}/bin/ls")
        (defconst my/nix-wakatime-cli "${pkgs.wakatime-cli}/bin/wakatime-cli")
      '';
      home.file.".emacs.d/early-init.el".source = ./emacs.d/early-init.el;
      # Home Manager joins all fragments above into the real init.el.
      home.file.".emacs.d/init.el".text = initEl;
    };
  };
}
